### PR TITLE
Re-Submission

### PR DESCRIPTION
**Pull request by phuard13**
Task 2

### CODE REVIEW

**Comment by Z11mm** [comment]
Please resolve these conflicts before your pull request can be merged.

**Comment by phuard13** [comment]
Pls I don't understand what should I do what is the error

Sent from Yahoo Mail on Android 
 
  On Fri, 5 Jun 2020 at 17:26, Zimuzo<notifications@github.com> wrote:   


Please resolve these conflicts before your pull request can be merged.

**Comment by phuard13** [comment]
I don't understand what I should do

**Comment by JoE11-y** [comment]
@phuard13 create another PR request.
In your forked repo create your file in the Submissions folder after that you can make a new PR to the submissions folder.

**Comment by phuard13** [comment]
I just did another PR created it in submission as requested HNG-01705

**Pull request closed without merging**
