### PR TITLE
Update HNG-01511.js

### PR DESCRIPTION
**Pull request by Chinzzyy26**
corrected HNG-01511.js removed the email variable and the email on its own in the string.

### CODE REVIEW

**Comment by JoE11-y** [comment]
Please resolve this conflict

**Comment by Babsmutini** [comment]
Please read the readme.md file to understand what your are doing. Ask questions on the team's channel if you are confused

**Comment by Chinzzyy26** [comment]
i've resolved conflicts

**Comment by Babsmutini** [comment]
It's not yet resolved

**Comment by JoE11-y** [comment]
You'll have to run on the command line from your end. if you can't do this close the PR and create a new one.

Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b Chinzzyy26-submissions submissions
git pull git://github.com/Chinzzyy26/HNG-Task-2-Team-Falcon.git submissions
Step 2: Merge the changes and update on GitHub.

git checkout submissions
git merge --no-ff Chinzzyy26-submissions
git push origin submissions

**Comment by Chinzzyy26** [comment]
Git checkout is saying it's not a git repository or any parent directory

**Pull request closed without merging**
