### PR TITLE
Create HNG-05556.js

### PR DESCRIPTION
**Pull request by super-beam**

### CODE REVIEW

**Comment by Babsmutini** [comment]
Hello, if this is merged, your file would wouldnt pass.
please you add your email variable/constant and pass it on to your console.log

**Comment by Babsmutini** [comment]
please review your code again
look at the readme.md file first, then do pull request to the submissions branch and not master

**Comment by super-beam** [comment]
@Babsmutini thanks, please review and if required please acknowledge what more changes should I make to get the script merged.

**Comment by super-beam** [comment]
@Babsmutini please review and acknowledge

**Comment by JoE11-y** [comment]
Much better now.

**Pull request merged**
