### PR TITLE
update from Francis- HNG-00379

### PR DESCRIPTION
**Pull request by ko74**

### CODE REVIEW

**Comment by Babsmutini** [comment]
make your pr requests to the submission branch

**Comment by ko74** [comment]
okay but how

**Comment by Babsmutini** [comment]
You can make a new pull request to the submissions branch of the teams repo

**Comment by ko74** [comment]
when I try that it says "can't automatically merge "

**Comment by Babsmutini** [comment]
read the readme.md file and follow the instructions again

**Comment by ko74** [comment]
okay

**Pull request closed without merging**
