### PR TITLE
Fixedbug

### PR DESCRIPTION
**Pull request by bolutej**

### CODE REVIEW

**Comment by Babsmutini** [comment]
Its conflicting

**Comment by bolutej** [comment]
i just fixed it

**Comment by Babsmutini** [comment]
Please change the pull request branch to submissions instead of master

**Comment by bolutej** [comment]
Ok on it

**Comment by Babsmutini** [comment]
the recent commit you made to submissions is having errors commiting you file

**Comment by bolutej** [comment]
have i fixed it now

**Comment by Babsmutini** [comment]
No. try make a pr all from the beginning.
That should solve it

**Pull request closed without merging**
