### PR TITLE
Create HNG-00379.py

### PR DESCRIPTION
**Pull request by ko74**
update from HNG-00379

### CODE REVIEW

**Comment by JoE11-y** [comment]
Screenshot_20200606-094328

Remove that and your script will pass. If merged now it will fail oo.

**Comment by ko74** [comment]
I should delete the email from the code

**Comment by JoE11-y** [comment]
Just erase that email. It's not meant to be there. Leave everything else untouched

**Comment by ko74** [comment]
okay

**Comment by ko74** [comment]
I have changed it please check it out

**Comment by JoE11-y** [comment]
Make a push to this PR. Or you make another PR

**Pull request closed without merging**
